x11-toolkits/qt6-quick3d: Fix bulk builds in poudriere
Quick3DRuntimeRender needs to build before QtQuick3D, so I'm not sure
why this include was added. Regressed by [1].

/wrkdirs/usr/ports/x11-toolkits/qt6-quick3d/work/qtquick3d-everywhere-src-6.6.0-beta2/src/runtimerender/rendererimpl/qssgrenderpass.c
fatal error: 'QtQuick3D/QQuick3DObject' file not found

[1] https://code.qt.io/cgit/qt/qtquick3d.git/commit/src?h=6.6&id=1bca206a3516875896b92508b0de9dcdaae7dfba